### ISSUE TITLE
Manages user on MariaDB 10.2 fail

### ISSUE THREAD

**Issue by HanXHX** [HanXHX/ansible-mysql#16] opened 2017-06-28 15:40 UTC
Due to this bug (https://github.com/ansible/ansible/issues/25960), MariaDB 10.2 cannot be managed by this role.

**Comment by jaspernbrouwer** [comment] 2017-07-05 18:37
When I use this role the first time on a new machine (I'm testing with vagrant: Debian Stretch on VirtualBox), installing MariaDB 10.2 from "upstream", everything goes smoothly. I'm _not_ hitting this issue.

After I perform a `apt-get dist-upgrade` on that machine, I _do_ hit this bug:

```
TASK [HanXHX.mysql : MYSQL_USER | Update mysql root password for all root accounts] **********************************
failed: [77.233.34.35] (item=********) => {"failed": true, "item": "********", "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 245}
failed: [77.233.34.35] (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1", "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 245}
failed: [77.233.34.35] (item=::1) => {"failed": true, "item": "::1", "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 245}
failed: [77.233.34.35] (item=localhost) => {"failed": true, "item": "localhost", "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 245}
```

`/var/log/messages` shows:

```
Jul  5 14:21:19 ******** ansible-mysql_user: Invoked with ssl_key=None update_password=always login_user=None host_all=False priv=None state=present sql_log_bin=True encrypted=False connect_timeout=30 config_file=/root/.my.cnf login_host=localhost append_privs=False login_unix_socket=None host=localhost user=root login_password=NOT_LOGGING_PARAMETER check_implicit_admin=False password=NOT_LOGGING_PARAMETER login_port=3306 ssl_cert=None name=root ssl_ca=None
Jul  5 14:21:19 ******** kernel: [3207230.583887] python[20219]: segfault at 0 ip 00007f5f42131464 sp 00007ffcaca0ed68 error 4 in libc-2.24.so[7f5f42007000+195000]
```

The only difference I'm able to find is in the version of the `libmariadbclient18` and `mysql-common` packages.

Fresh install:

```
$ dpkg-query -l | grep mysql-common
ii  mysql-common                  5.8+1.0.2                      all          MySQL database common files, e.g. /etc/mysql/my.cnf

$ dpkg-query -l | grep libmariadbclient18
ii  libmariadbclient18:amd64      10.1.23-9+deb9u1               amd64        MariaDB database client library
```

After `apt-get dist-upgrade`:

```
$ dpkg-query -l | grep mysql-common
ii  mysql-common                  10.2.6+maria~stretch           all          MariaDB database common files (e.g. /etc/mysql/my.cnf)

$ dpkg-query -l | grep libmariadbclient18
ii  libmariadbclient18            10.2.6+maria~stretch           amd64        Virtual package to satisfy external depends
```

The `apt-get dist-upgrade` does upgrade (among others) these 2 packages. I'm not sure why the initial install uses Debian's own versions, and only after a `apt-get dist-upgrade` the versions from MariaDB's repository are used. I'm even more confused about that using the versions from MariaDB's repository actually breaks things.

**Comment by HanXHX** [comment] 2017-07-05 22:39
Yep :(

You can bypass the problem by installing latest version of python mysqlclient with pip. It's dirty but it works 🤢

**Comment by jaspernbrouwer** [comment] 2017-07-06 13:51
May I ask _how_ you're installing `mysqlclient` through pip?

I'm starting with MariaDB 10.2 on Debian Stretch in the broken situation:

```
$ dpkg-query -l | grep mysql-common
ii  mysql-common                  10.2.6+maria~stretch           all          MariaDB database common files (e.g. /etc/mysql/my.cnf)

$ dpkg-query -l | grep libmariadbclient18
ii  libmariadbclient18            10.2.6+maria~stretch           amd64        Virtual package to satisfy external depends
```

I first need to install `libmariadb-dev`:

```
$ sudo apt-get install libmariadb-dev
```

Then I proceed installing `mysqlclient` through pip:

```
$ sudo pip install mysqlclient
Collecting mysqlclient
  Downloading mysqlclient-1.3.10.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 3.5MB/s
Building wheels for collected packages: mysqlclient
  Running setup.py bdist_wheel for mysqlclient ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Zy1nWG/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpcSQu0wpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/compat.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb
  creating build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
  running build_ext
  building '_mysql' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Dversion_info=(1,3,10,'final',0) -D__version__=1.3.10 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
  In file included from _mysql.c:30:0:
  /usr/include/mysql/mysql.h:438:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     MYSQL_CLIENT_PLUGIN_HEADER
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/mysql/mysql.h:583:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   my_bool STDCALL mysql_embedded();
   ^~~~~~~
  _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
  _mysql.c:1911:41: error: ‘MYSQL {aka struct st_mysql}’ has no member named ‘reconnect’
    if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                           ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mysqlclient
  Running setup.py clean for mysqlclient
Failed to build mysqlclient
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Zy1nWG/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GXeQgA-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/compat.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb
    creating build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    running build_ext
    building '_mysql' extension
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Dversion_info=(1,3,10,'final',0) -D__version__=1.3.10 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
    In file included from _mysql.c:30:0:
    /usr/include/mysql/mysql.h:438:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
       MYSQL_CLIENT_PLUGIN_HEADER
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/mysql/mysql.h:583:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     my_bool STDCALL mysql_embedded();
     ^~~~~~~
    _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
    _mysql.c:1911:41: error: ‘MYSQL {aka struct st_mysql}’ has no member named ‘reconnect’
      if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                             ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Zy1nWG/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GXeQgA-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Zy1nWG/mysqlclient/
```

As you can see I'm hitting the issue fixed by https://github.com/PyMySQL/mysqlclient-python/pull/177.

The problem is, this fix hasn't been released yet. I can manually download the `master` version and install that, but that's even more 🤢

**Closed as completed** 2019-12-21 15:22 UTC
Labels: bug, wontfix
